### ISSUE TITLE
Site is not available

### ISSUE THREAD

**Issue by sagdeev** [juliancwirko/s-grid#11]
http://stylusgrid.com/ not working:(

**Comment by juliancwirko** [comment]
Hi, it works for me now, could you check again?

**Comment by sagdeev** [comment]
Hmm, interesting. From Russia not working `¯\_(ツ)_/¯`
Through the VPN everything is ok

![2017-07-28 15 37 57](https://user-images.githubusercontent.com/8946162/28715828-e7e8f4b0-73aa-11e7-97b6-566c767f3ebb.png)

**Comment by juliancwirko** [comment]
oh, this is weird ;) I have no idea why. 
It is hosted on shared hosting so maybe the ip range is banned in Russia.

**Comment by sagdeev** [comment]
Maybe. Will use VPN :)
Thanks!
