### ISSUE TITLE
Fallback for calc()

### ISSUE THREAD

**Issue by Julien76** [juliancwirko/s-grid#3]
Hi,

I'm using s-grid and it is very handy to set-up flexbox grid. It works greats for the most. However it does seems to fail for IE10 and Safari on ios8.
I can't check why on ios8 but on IE10, none of the attributes using calc() are used (they are greyed out), for example:

![capture](https://cloud.githubusercontent.com/assets/1630303/13425483/533d6bcc-dfa7-11e5-9559-b9e434f2b920.PNG)

Will it be possible to add a fallback for calc() for browser that does not handle well it?
Please let me know if you need more input from me.

Thanks.

**Comment by juliancwirko** [comment]
Hi the calc() should work in ie10 and ios see: http://caniuse.com/#search=calc maybe this is the case of flexbox or vh units. do you use autoprefixer with this grid? 

Unfortunatelly I don't plan to support ie10 or below.

**Comment by Julien76** [comment]
Hi,
Yes I'm using autoprefixer.
That's true that I'm using vh units.
I'm trying to understand why it does work and the only real thing I can see is that IE 10 crossed out all the lines where calc() is used.

**Comment by juliancwirko** [comment]
Hard to tell :/ It probably needs some more investigation. Do you have this website online?

**Comment by Julien76** [comment]
the website is not finished and need some clean-up, but you can find a temporary version here:
[julienhericher.com](url)

**Comment by juliancwirko** [comment]
Hi, sorry for the delay. I think that IE11 and Edge could have some problems with flexbox. It is described here: https://github.com/philipwalton/flexbugs it could be related with this bug: https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box

**Comment by juliancwirko** [comment]
I'll try to provide a fix for this, because teoretically it could be done and I think I've fixed it on the stylusgrid.com website, but I am not sure if I'll be able to provide universal solution in the sGrid. I'll keep you posted.

**Comment by juliancwirko** [comment]
Ok, so I can't provide universal solution in sGrid because this depends on your custom styling. You can provide another wrapper which will have all your paddings and borders etc. Take a look at: https://github.com/philipwalton/flexbugs#workaround-6 point 2.

**Comment by Julien76** [comment]
Hi,
Thanks a lot for your support and very sorry for this more-than-late reply, I had to be away from my pc for other reason... I move a pure css flex box implementation to cope with IE10.
Thanks again.
