### ISSUE TITLE
How to use this with PostCSS?

### ISSUE THREAD

**Issue by purezen** [juliancwirko/s-grid#4]
Hi,
I had been working on an app where I used sGid to implement a grid system. But now we have implemented PostCSS in our app. I am not sure if this is the way to go, but can I implement grid system using sGrid in my app? If so, how?

**Comment by juliancwirko** [comment]
Hi, this is of course possible. PostCSS can work with Stylus side by side. You can check the Grunt boilerplate with sGrid here: https://github.com/juliancwirko/s-grid-grunt you only need to add [grunt-postcss](https://github.com/nDmitry/grunt-postcss) plugin.

Or if you are using Webpack take a look at: https://github.com/juliancwirko/react-boilerplate there is sGrid and PostCSS implemented.
