### ISSUE TITLE
failed to locate @import file s-grid-settings.styl

### ISSUE THREAD

**Issue by eakl** [juliancwirko/s-grid#6]
Hi,

I cannot import s-grid in a stylus file.

What I've done 

```
xxx@xxxl:~$ sudo npm install -g s-grid
/usr/local/lib
└── s-grid@1.2.0
```

Then I got this error

```
xxx@xxx:~$ stylus -w ./project/css/app.styl -o ./project/css/app.css
  watching /usr/local/lib/node_modules/stylus/lib/functions/index.styl
Error: project/css/app.styl:1:9
   1| @import 's-grid-settings'
--------------^
   2| @import 's-grid-functions'
   3| @import 's-grid-classes'
   4| 

failed to locate @import file s-grid-settings.styl
```

My app.styl file is:

```
@import 's-grid-settings'
@import 's-grid-functions'
@import 's-grid-classes'

header
    background-color: #eee
```

Is there any known issue or something I did wrong ?

I just followed [this tutorial](https://www.sitepoint.com/introducing-sgrid-a-stylus-based-flexbox-grid-system/) without installing autoprefixer

**Comment by juliancwirko** [comment]
Looks like it can't find it in the global scope. You can try to install it locally in your project's root folder, by `npm install s-grid`. It's hard to say what could go wrong. It could depend on your OS configuration etc. Let me know if it works in local scope. Thanks. You may also want to check out some ready to use boilerplates: http://stylusgrid.com/getting-started.html If you want to use it standalone remember to add Autoprefixer to your stylus workflow.

**Comment by eakl** [comment]
Installed locally, it doesn't work neither. At least with a `@import 's-grid-settings'`.
However, it works with a `@import '../../node_modules/s-grid/s-grid-settings'`.

**Comment by eakl** [comment]
OK, `@import 's-grid-*'` works when adding `-u s-grid` to the command line.
Former command: `stylus -w ./project/css/app.styl -o ./project/css/app.css`
New one: `stylus -u s-grid -w ./project/css/app.styl -o ./project/css/app.css`

**Comment by juliancwirko** [comment]
yeah, I was about to write ;) In your case you need something like:

```
$ stylus -u s-grid -u autoprefixer-stylus -w main.styl
```

then it should also work with global installation... sorry, I forgot about it ;) 

This is why it is better to use a boilerplate ;)

**Comment by eakl** [comment]
Yes, it also works with global.
Thanks @juliancwirko, you helped me think about the problem ;)
