### ISSUE TITLE
Make column fit content?

### ISSUE THREAD

**Issue by FezVrasta** [juliancwirko/s-grid#7]
With flex I could do:

```
.grid
  display: flex
  &__col
    &--fit
      flex: 1
```

```
<div class='grid'>
  <div class='grid__col grid__col--fit'>foo</div>
  <div class='grid__col'>bar</div>
</div>
```

And I would have the `foo` column which takes all the available space, excluded the space used by `bar`.

With s-grid I'm trying to do so:

```
.grid
  grid()
  &__col
    &--fit
      cell-offset(4, 8)
      cell(3, 8)
```

But when the page gets too small, the `bar` column goes on a new line.

**Comment by juliancwirko** [comment]
Hmm I get your point, but I wonder if we need any additional functionalities in sGrid to achieve it, but maybe I've misunderstood you. Because let's see:
1. Of course You can always use pure flexbox styles and in this case it is very simple.
   OR
2. You can do something like:

```
// html
<div class='grid'>
  <div class='grid__col grid__col--left'>foo</div>
  <div class='grid__col grid__col--right'>bar</div>
</div>

// stylus:
.grid
  grid()
  &__col
    &--left
      cell(3, 8)
    &--right
      cell(5, 8)

```

**Comment by juliancwirko** [comment]
You can always repen the issue if you want. Thanks.
