### ISSUE TITLE
how to remove first and last margin of grid elements

### ISSUE THREAD

**Issue by ghisleouf** [juliancwirko/s-grid#8]
Hello,

Is there a way to easily remove the margin related to first and last element of my grid ?

For example, let's consider this html structure :

```html
<div class="row">
     <div href="#" class="block" >
         <img src="http://lorempixel.com/400/225/sports/1" class="block__picture"/>
         <h3 class="block__title" >Fluctus de varius fluctui, amor clabulare!</h3>
     </div>
     <div href="#" class="block" >
         <img src="http://lorempixel.com/400/225/sports/1" class="block__picture"/>
         <h3 class="block__title" >Fluctus de varius fluctui, amor clabulare!</h3>
     </div>
     <div href="#" class="block" >
         <img src="http://lorempixel.com/400/225/sports/1" class="block__picture"/>
         <h3 class="block__title" >Fluctus de varius fluctui, amor clabulare!</h3>
     </div>
     <div href="#" class="block" >
         <img src="http://lorempixel.com/400/225/sports/1" class="block__picture"/>
         <h3 class="block__title" >Fluctus de varius fluctui, amor clabulare!</h3>
     </div>
 </div>
```
 and this stylus code :

```css
.row {
  grid(direction: 'row', cells-align: 'stretch')
}
.block {
  cell(1, 4)
}
```

Automatically, all my ".block" elements will have a 10px right margin but I would like to remove this margin on the first and last element of the list.
Is there a a way to achieve it ?

Thanks for your help !

**Comment by juliancwirko** [comment]
Hi you can use gutter, for example: `cell(1, 4, g: 0)`

**Comment by ghisleouf** [comment]
Hello,

The thing is if I do that, it will remove all the gutters between each elements, not only the first and the last.

I was thinking about something like adding negative margin right and left to the parent element (.row ).

```css 
margin-left: -0.625rem
margin-right: -0.625rem
```

Thanks for your help.

**Comment by juliancwirko** [comment]
Oh ok, I don't think that negative spacing is a good idea, but you can try, you can also use grid elements as wrappers and put inside something with margins or paddings using standard css.
